apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streamlit
    spec:
      containers:
      - image: sureshrajaperumal/gs-house-predictor/streamlit:latest
        imagePullPolicy: Always
        name: streamlit
        ports:
        - containerPort: 8501
        resources: {}
status: {}
